baseURL = "https://softDmg.github.io/"
languageCode = "en-us"
title = "Maidawa"
theme = "bearblog"

enableRobotsTXT = true

[params]
  description = "Research, systems, teaching, football, and some humour"
customCSS = ["css/custom.css"]
